"""add_room_search_vector

Revision ID: 01426aafb93a
Revises: 60e0653f69e1
Create Date: 2026-05-18 01:43:20.721921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01426aafb93a"
down_revision: Union[str, Sequence[str], None] = "60e0653f69e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_room_search_trgm",
        "room",
        [sa.literal_column("(title || ' ' || description)")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"(title || ' ' || description)": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_room_search_trgm",
        table_name="room",
        postgresql_using="gin",
        postgresql_ops={"(title || ' ' || description)": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
