"""create_sessions_tables

Revision ID: 1407974b35b9
Revises: d62a535011d7
Create Date: 2026-03-20 19:43:51.182660

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1407974b35b9"
down_revision: Union[str, Sequence[str], None] = "d62a535011d7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "session",
        sa.Column("room_id", sa.BigInteger(), nullable=False),
        sa.Column("quiz_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column(
            "description",
            sa.String(length=500),
            server_default=sa.text("''"),
            nullable=False,
        ),
        sa.Column("time_seconds", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("waiting", "active", "completed", name="session_status"),
            server_default=sa.text("'waiting'"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "time_seconds <= 604800", name="chk_less_equal_week_time_seconds"
        ),
        sa.CheckConstraint("time_seconds > 0", name="chk_positive_time_seconds"),
        sa.ForeignKeyConstraint(
            ["quiz_id"], ["quiz.id"], onupdate="CASCADE", ondelete="NO ACTION"
        ),
        sa.ForeignKeyConstraint(
            ["room_id"], ["room.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_session_quiz_id"), "session", ["quiz_id"], unique=False)
    op.create_index(op.f("ix_session_room_id"), "session", ["room_id"], unique=False)
    op.create_table(
        "session_member",
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["session.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "user_id", name="uq_session_member_session_user"
        ),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_session_member_session_id"),
        "session_member",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_member_user_id"), "session_member", ["user_id"], unique=False
    )
    op.create_table(
        "session_question",
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.String(length=500), nullable=False),
        sa.Column("is_multiple_answers", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["session.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_session_question_session_id"),
        "session_question",
        ["session_id"],
        unique=False,
    )
    op.create_table(
        "session_question_option",
        sa.Column("session_question_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.String(length=500), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["session_question_id"],
            ["session_question.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_session_question_option_session_question_id"),
        "session_question_option",
        ["session_question_id"],
        unique=False,
    )
    op.create_table(
        "session_member_answer",
        sa.Column("session_question_id", sa.BigInteger(), nullable=False),
        sa.Column("session_question_option_id", sa.BigInteger(), nullable=False),
        sa.Column("session_member_id", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["session_member_id"],
            ["session_member.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_question_id"],
            ["session_question.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_question_option_id"],
            ["session_question_option.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_member_id",
            "session_question_id",
            "session_question_option_id",
            name="uq_session_member_answer",
        ),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_session_member_answer_session_member_id"),
        "session_member_answer",
        ["session_member_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_member_answer_session_question_id"),
        "session_member_answer",
        ["session_question_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_session_member_answer_session_question_option_id"),
        "session_member_answer",
        ["session_question_option_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_session_member_answer_session_question_option_id"),
        table_name="session_member_answer",
    )
    op.drop_index(
        op.f("ix_session_member_answer_session_question_id"),
        table_name="session_member_answer",
    )
    op.drop_index(
        op.f("ix_session_member_answer_session_member_id"),
        table_name="session_member_answer",
    )
    op.drop_table("session_member_answer")
    op.drop_index(
        op.f("ix_session_question_option_session_question_id"),
        table_name="session_question_option",
    )
    op.drop_table("session_question_option")
    op.drop_index(op.f("ix_session_question_session_id"), table_name="session_question")
    op.drop_table("session_question")
    op.drop_index(op.f("ix_session_member_user_id"), table_name="session_member")
    op.drop_index(op.f("ix_session_member_session_id"), table_name="session_member")
    op.drop_table("session_member")
    op.drop_index(op.f("ix_session_room_id"), table_name="session")
    op.drop_index(op.f("ix_session_quiz_id"), table_name="session")
    op.drop_table("session")
    # ### end Alembic commands ###
