"""enforce_data_integrity_and_quiz_soft_delete

Revision ID: 1f038ffcff07
Revises: 1407974b35b9
Create Date: 2026-03-24 18:09:33.331123

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1f038ffcff07"
down_revision: Union[str, Sequence[str], None] = "1407974b35b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_constraint(op.f("quiz_creator_id_fkey"), "quiz", type_="foreignkey")
    op.create_foreign_key(
        None,
        "quiz",
        "user",
        ["creator_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.drop_constraint(op.f("room_creator_id_fkey"), "room", type_="foreignkey")
    op.create_foreign_key(
        None,
        "room",
        "user",
        ["creator_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.drop_constraint(op.f("session_room_id_fkey"), "session", type_="foreignkey")
    op.drop_constraint(op.f("session_quiz_id_fkey"), "session", type_="foreignkey")
    op.create_foreign_key(
        None,
        "session",
        "quiz",
        ["quiz_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        None,
        "session",
        "room",
        ["room_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.drop_constraint(
        op.f("session_member_user_id_fkey"), "session_member", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "session_member",
        "user",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "session_member", type_="foreignkey")
    op.create_foreign_key(
        op.f("session_member_user_id_fkey"),
        "session_member",
        "user",
        ["user_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "session", type_="foreignkey")
    op.drop_constraint(None, "session", type_="foreignkey")
    op.create_foreign_key(
        op.f("session_quiz_id_fkey"),
        "session",
        "quiz",
        ["quiz_id"],
        ["id"],
        onupdate="CASCADE",
    )
    op.create_foreign_key(
        op.f("session_room_id_fkey"),
        "session",
        "room",
        ["room_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "room", type_="foreignkey")
    op.create_foreign_key(
        op.f("room_creator_id_fkey"),
        "room",
        "user",
        ["creator_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_constraint(None, "quiz", type_="foreignkey")
    op.create_foreign_key(
        op.f("quiz_creator_id_fkey"),
        "quiz",
        "user",
        ["creator_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.drop_column("quiz", "deleted_at")
    # ### end Alembic commands ###
