"""add_quiz_search_vector

Revision ID: 60e0653f69e1
Revises: 7ba113ccaa93
Create Date: 2026-05-18 01:42:20.869904

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60e0653f69e1"
down_revision: Union[str, Sequence[str], None] = "7ba113ccaa93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_quiz_search_trgm",
        "quiz",
        [sa.literal_column("(title || ' ' || description)")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"(title || ' ' || description)": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_quiz_search_trgm",
        table_name="quiz",
        postgresql_using="gin",
        postgresql_ops={"(title || ' ' || description)": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
