"""change_quiz_column_name

Revision ID: 6322be3b418b
Revises: 8e044bd6faaf
Create Date: 2026-02-16 16:20:12.375745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6322be3b418b"
down_revision: Union[str, Sequence[str], None] = "8e044bd6faaf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("quiz", sa.Column("title", sa.String(length=100), nullable=False))
    op.drop_column("quiz", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz",
        sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.drop_column("quiz", "title")
    # ### end Alembic commands ###
