"""add_quiz_column_server_default

Revision ID: 841d45af46d6
Revises: c40d5fa1924a
Create Date: 2026-03-10 19:19:21.239405

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "841d45af46d6"
down_revision: Union[str, Sequence[str], None] = "c40d5fa1924a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quiz",
        "description",
        existing_type=sa.VARCHAR(length=500),
        server_default=sa.text("''"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "quiz",
        "description",
        existing_type=sa.VARCHAR(length=500),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
