"""create_quizzes_tables

Revision ID: 8e044bd6faaf
Revises: 08984138a2ab
Create Date: 2026-02-15 18:42:07.134529

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8e044bd6faaf"
down_revision: Union[str, Sequence[str], None] = "08984138a2ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz",
        sa.Column("creator_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("is_public", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["creator_id"], ["user.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_quiz_creator_id"), "quiz", ["creator_id"], unique=False)
    op.create_table(
        "quiz_question",
        sa.Column("quiz_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.String(length=500), nullable=False),
        sa.Column("is_multiple_answers", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["quiz_id"], ["quiz.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_quiz_question_quiz_id"), "quiz_question", ["quiz_id"], unique=False
    )
    op.create_table(
        "quiz_question_option",
        sa.Column("quiz_question_id", sa.BigInteger(), nullable=False),
        sa.Column("text", sa.String(length=500), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "uuid", sa.Uuid(), server_default=sa.text("uuidv7()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["quiz_question_id"],
            ["quiz_question.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_quiz_question_option_quiz_question_id"),
        "quiz_question_option",
        ["quiz_question_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quiz_question_option_quiz_question_id"),
        table_name="quiz_question_option",
    )
    op.drop_table("quiz_question_option")
    op.drop_index(op.f("ix_quiz_question_quiz_id"), table_name="quiz_question")
    op.drop_table("quiz_question")
    op.drop_index(op.f("ix_quiz_creator_id"), table_name="quiz")
    op.drop_table("quiz")
    # ### end Alembic commands ###
