"""add_session_search_vector

Revision ID: e4ed135f6e3d
Revises: 01426aafb93a
Create Date: 2026-05-18 02:08:53.150536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4ed135f6e3d"
down_revision: Union[str, Sequence[str], None] = "01426aafb93a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_session_search_trgm",
        "session",
        [sa.literal_column("(title || ' ' || description)")],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"(title || ' ' || description)": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_session_search_trgm",
        table_name="session",
        postgresql_using="gin",
        postgresql_ops={"(title || ' ' || description)": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
